[project]
name = "clockwork"
version = "0.1.0"
description = "Ultra-simple, agent-assisted infrastructure tool with deterministic core"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-hcl2>=7.3.1",
    "typer>=0.16.0",
    "pydantic>=2.0.0",
    "rich>=13.0.0",
]

[project.scripts]
clockwork = "clockwork.cli:app"
