"""
File Generation Example - Simple file creation with Clockwork.

This example demonstrates basic file creation with all fields specified.
"""

from clockwork.resources import FileResource
from clockwork.assertions import (
    FileExistsAssert,
    FileContentMatchesAssert,
)

# Example file with user-provided content
readme = FileResource(
    description="README file explaining the example",
    name="README.md",
    directory="scratch",
    content="""# File Generation Example

This directory contains files generated by Clockwork.

## What is Clockwork?

Clockwork is an intelligent infrastructure orchestration tool that uses:
- Python for declarative infrastructure definitions
- Pulumi for cross-platform automation
- AI for intelligent resource completion

## How it Works

1. Define resources in Python using Pydantic models
2. Clockwork compiles to Pulumi operations
3. Pulumi executes the operations via Automation API
4. Assertions validate the deployed state

Generated with Clockwork
""",
    mode="644",
    assertions=[
        FileExistsAssert(path="scratch/README.md"),
        FileContentMatchesAssert(
            path="scratch/README.md",
            pattern="Clockwork"
        ),
    ]
)
