"""
File Generation Example - Simplified Clockwork with AI-powered completion.

This example demonstrates:
- MINIMAL: FileResource with just a description (AI completes everything)
- ADVANCED: FileResource with description + selective overrides
- Type-safe assertions for file validation
"""

from clockwork.resources import FileResource
from clockwork.assertions import (
    FileExistsAssert,
    FileSizeAssert,
    FileContentMatchesAssert,
)

# MINIMAL EXAMPLE - AI completes name, content, directory, mode
# Just provide description, AI handles the rest
game_of_life = FileResource(
    description="Comprehensive article about Conway's Game of Life, including history, rules, and significance"
)
# AI will generate:
# - name: "game_of_life.md" (or similar)
# - content: full article content
# - directory: "." (current directory)
# - mode: "644"

# ADVANCED EXAMPLE - Override specific fields
# Provide description + override directory and customize assertions
poem = FileResource(
    description="Short poem about infrastructure automation and declarative configuration",
    directory="scratch",  # Override: put in scratch directory
    assertions=[
        # Custom assertions (need to know the directory override)
        FileSizeAssert(
            path="scratch/clockwork_poem.txt",  # Assumes AI names it clockwork_poem.txt
            min_bytes=50,
            max_bytes=2000
        ),
    ]
)

# USER-PROVIDED CONTENT - Skip AI generation entirely
readme = FileResource(
    description="README file explaining the generated files",
    name="README.md",
    directory="scratch",
    content="""# Generated Files

This directory contains files generated by Clockwork:

- `game_of_life.md` - Comprehensive article (AI-generated)
- `clockwork_poem.txt` - Short poem (AI-generated)
- `README.md` - This file (user-provided)

Generated with Clockwork
""",
    assertions=[
        FileExistsAssert(path="scratch/README.md"),
        FileContentMatchesAssert(
            path="scratch/README.md",
            pattern="Generated Files"
        ),
    ]
)
