"""
File Generation Example - Clockwork with AI-powered content generation.

This example demonstrates:
- FileResource with AI-generated content (description only)
- FileResource with user-provided content
- Size hints for AI generation (SMALL, MEDIUM, LARGE)
- Type-safe assertions for file validation
"""

from clockwork.resources import FileResource, ArtifactSize
from clockwork.assertions import (
    FileExistsAssert,
    FileSizeAssert,
    FileContentMatchesAssert,
)

# AI generates content based on description
game_of_life = FileResource(
    name="game_of_life.md",
    description="Write a comprehensive article about Conway's Game of Life, including its history, rules, and significance in computer science",
    size=ArtifactSize.MEDIUM,
    directory="scratch",
    assertions=[
        # Type-safe assertions for file existence and size
        FileExistsAssert(path="scratch/game_of_life.md"),
        FileSizeAssert(
            path="scratch/game_of_life.md",
            min_bytes=500,  # At least 500 bytes for a comprehensive article
            max_bytes=50000  # Not more than 50KB
        ),
        # Content validation using type-safe assertion
        FileContentMatchesAssert(
            path="scratch/game_of_life.md",
            pattern="Conway"
        ),
    ]
)

# AI generates a small poem
poem = FileResource(
    name="clockwork_poem.txt",
    description="Write a short poem about infrastructure automation and the beauty of declarative configuration",
    size=ArtifactSize.SMALL,
    directory="scratch",
    assertions=[
        # Type-safe assertions
        FileExistsAssert(path="scratch/clockwork_poem.txt"),
        FileSizeAssert(
            path="scratch/clockwork_poem.txt",
            min_bytes=50,  # At least 50 bytes for a short poem
            max_bytes=2000  # Keep it under 2KB for a short poem
        ),
    ]
)

# User provides content directly (no AI generation)
readme = FileResource(
    name="README.md",
    description="Not used - content is provided",
    content="""# Generated Files

This directory contains files generated by Clockwork:

- `game_of_life.md` - Article about Conway's Game of Life (AI-generated)
- `clockwork_poem.txt` - Poem about infrastructure automation (AI-generated)
- `README.md` - This file (user-provided)

Generated with Clockwork ❤️
""",
    directory="scratch",
    assertions=[
        # Type-safe assertions
        FileExistsAssert(path="scratch/README.md"),
        FileContentMatchesAssert(
            path="scratch/README.md",
            pattern="Generated Files"
        ),
    ]
)
